### ISSUE TITLE
Libmesh not picking up TBB version

### ISSUE THREAD

**Issue by tradowsk** [ubceslab/swenv#2]
The libmesh module file for some reason does not pick up the tbb version in the modulefile, making `module load libmesh` fail due to a non-existent directory.

**Comment by pbauman** [comment]
Do a pull on this repo and rebuild lib mesh using the build script. I'd forgotten we need to do TBB_VERSIONNUM (or something else other than TBB_VERSION) because TBB uses that in one of their headers.

**Comment by tradowsk** [comment]
Did you mean to push something, because nothing seems different

**Comment by pbauman** [comment]
All my build scripts looked updated and my status is clean. srcgrep for TBB_VERSIONNUM

**Comment by tradowsk** [comment]
My bad, my local repo was not sync'd with the upstream one.

Everything looks okay.
